---
  - hosts: local
    sudo: yes 
    tasks:
        - name: go to tmp directory
          command: chdir=/tmp/ ls
        - name: if Code dir is empty create new play app
          raw: "if [ ! '$(ls -A /home/play/Code)']; then activator new tempapp play-scala ; fi;"
        - name: move new app to Code Dir
          raw: "if [ ! '$(ls -A /home/play/Code)']; then mv -v /tmp/tempapp/* /home/play/Code/ ; fi;"
        - name: move to Code dir and run activator
          command: chdir=/home/play/Code /opt/activator/activator

        
